Traceback (most recent call last):
  File "misc/math.py", line 261, in <module>
    resp = evalSym(*i[:-1])
  File "misc/math.py", line 197, in evalSym
    f = parser.parse_expr(
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\parsing\sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\parsing\sympy_parser.py", line 902, in eval_expr
    expr = eval(
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc9a' in position 13: surrogates not allowed
['âˆ\udc9a3', '64', '0', '247184721262411776']Traceback (most recent call last):
  File "misc/math.py", line 264, in <module>
    resp = evalSym(*i[:-1])
  File "misc/math.py", line 197, in evalSym
    f = parser.parse_expr(
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\parsing\sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\parsing\sympy_parser.py", line 902, in eval_expr
    expr = eval(
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc9a' in position 13: surrogates not allowed
